# Generated by Django 4.2.17 on 2025-01-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_bookingmodel_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingModel',
            new_name='booking',
        ),
        migrations.RenameModel(
            old_name='menuModel',
            new_name='menu',
        ),
    ]
